= Welcome to My product!

This is the automatic start page for version *{page-product-version}* of product B.

product B is one of two documentation products in the Antora Demo.
The other docs product, product A, can be accessed via the product selector menu (aka product drawer) at the bottom of the menu on the left side of the page.

== Page source

This page is sourced from the AsciiDoc file named [.path]_index.adoc_ that is located at [.path]_demo-product-b/docs/modules/ROOT/pages_.

=== Why is this the home page of product B?

This page is automatically used as the start page of product B because it is stored in the ROOT module and named [.path]_index.adoc_.

=== Why is this the home page of the Antora Demo site?

This page is used as the home page for the Antora Demo because it is assigned as the site `start_page` in the Demo site's playbook file [.path]_site.yml_.

== Cross reference syntax to target this page

To create a cross reference *to this page from another page in the ROOT module of product B*, the xref syntax would be `\xref:index.adoc[]`.

To create a cross reference *to this page from a page in Module One of product B*, the xref syntax would be `\xref:ROOT:index.adoc[]`.

=== Always target the latest version of this page

To create a cross reference *to the latest version of this page from a page in product A*, the xref syntax would be `\xref:product-b::index.adoc[]`.

=== Target a specific version of this page

To create a cross reference *to version 1.0 of this page from a page in product A*, the xref syntax would be `\xref:1.0@product-b::index.adoc[]`.
